var tree = [["[Global Namespace]",,"",
                [["SplClassLoader","SplClassLoader.html","",
                [        ]]        ]],["Patterns",,"",
                [["Abstracts","Patterns\/Abstracts.html","",
                [["AbstractAccessible","Patterns\/Abstracts\/AbstractAccessible.html","",
                [        ]],["AbstractOptionable","Patterns\/Abstracts\/AbstractOptionable.html","",
                [        ]],["AbstractResponse","Patterns\/Abstracts\/AbstractResponse.html","",
                [        ]],["AbstractSingleton","Patterns\/Abstracts\/AbstractSingleton.html","",
                [        ]],["AbstractStaticCreator","Patterns\/Abstracts\/AbstractStaticCreator.html","",
                [        ]],["AbstractView","Patterns\/Abstracts\/AbstractView.html","",
                [        ]]        ]],["Commons","Patterns\/Commons.html","",
                [["Collection","Patterns\/Commons\/Collection.html","",
                [        ]],["ConfigurationRegistry","Patterns\/Commons\/ConfigurationRegistry.html","",
                [        ]],["Registry","Patterns\/Commons\/Registry.html","",
                [        ]]        ]],["Interfaces","Patterns\/Interfaces.html","",
                [["ArrayInterface","Patterns\/Interfaces\/ArrayInterface.html","",
                [        ]],["CachableInterface","Patterns\/Interfaces\/CachableInterface.html","",
                [        ]],["CollectionInterface","Patterns\/Interfaces\/CollectionInterface.html","",
                [        ]],["CrudInterface","Patterns\/Interfaces\/CrudInterface.html","",
                [        ]],["DebuggableInterface","Patterns\/Interfaces\/DebuggableInterface.html","",
                [        ]],["IteratorInterface","Patterns\/Interfaces\/IteratorInterface.html","",
                [        ]],["OptionableInterface","Patterns\/Interfaces\/OptionableInterface.html","",
                [        ]],["RepositoryInterface","Patterns\/Interfaces\/RepositoryInterface.html","",
                [        ]],["ResponseInterface","Patterns\/Interfaces\/ResponseInterface.html","",
                [        ]],["RouterInterface","Patterns\/Interfaces\/RouterInterface.html","",
                [        ]],["StaticCreatorInterface","Patterns\/Interfaces\/StaticCreatorInterface.html","",
                [        ]],["StaticOptionableInterface","Patterns\/Interfaces\/StaticOptionableInterface.html","",
                [        ]],["TranslatableInterface","Patterns\/Interfaces\/TranslatableInterface.html","",
                [        ]],["UserInterface","Patterns\/Interfaces\/UserInterface.html","",
                [        ]],["ViewInterface","Patterns\/Interfaces\/ViewInterface.html","",
                [        ]],["WebPageInterface","Patterns\/Interfaces\/WebPageInterface.html","",
                [        ]]        ]]        ]]        ]

