var tree = [["[Global Namespace]",,"",
                [["SplClassLoader","SplClassLoader.html","",
                [        ]]        ]],["Patterns",,"",
                [["Abstracts","Patterns\/Abstracts.html","",
                [["AbstractAccessible","Patterns\/Abstracts\/AbstractAccessible.html","",
                [        ]],["AbstractSingleton","Patterns\/Abstracts\/AbstractSingleton.html","",
                [        ]]        ]],["Commons","Patterns\/Commons.html","",
                [["Collection","Patterns\/Commons\/Collection.html","",
                [        ]]        ]],["Interfaces","Patterns\/Interfaces.html","",
                [["ArrayInterface","Patterns\/Interfaces\/ArrayInterface.html","",
                [        ]],["CollectionInterface","Patterns\/Interfaces\/CollectionInterface.html","",
                [        ]],["CrudInterface","Patterns\/Interfaces\/CrudInterface.html","",
                [        ]],["DebuggableInterface","Patterns\/Interfaces\/DebuggableInterface.html","",
                [        ]],["IteratorInterface","Patterns\/Interfaces\/IteratorInterface.html","",
                [        ]],["OptionableInterface","Patterns\/Interfaces\/OptionableInterface.html","",
                [        ]],["RepositoryInterface","Patterns\/Interfaces\/RepositoryInterface.html","",
                [        ]],["RouterInterface","Patterns\/Interfaces\/RouterInterface.html","",
                [        ]],["TranslatableInterface","Patterns\/Interfaces\/TranslatableInterface.html","",
                [        ]],["UserInterface","Patterns\/Interfaces\/UserInterface.html","",
                [        ]],["ViewInterface","Patterns\/Interfaces\/ViewInterface.html","",
                [        ]],["WebPageInterface","Patterns\/Interfaces\/WebPageInterface.html","",
                [        ]]        ]]        ]]        ]

